# SPDX-FileCopyrightText: 2021-2024 Taavi Väänänen <hi@taavi.wtf>
# SPDX-License-Identifier: AGPL-3.0-only

DATABASE:
  HOST: 127.0.0.1
  DATABASE: prometheusconfig
  USER:
    USERNAME: prometheusconfig
    PASSWORD: prometheusconfig
  ADMIN:
    USERNAME: prometheusconfigadmin
    PASSWORD: prometheusconfigadmin

OPENSTACK:
  CONFIG: /etc/novaobserver.yaml
