"""add phab alert target

Revision ID: 0db5740c2d4c
Revises: a560c23bf970
Create Date: 2025-05-28 11:54:59.453188

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0db5740c2d4c"
down_revision = "a560c23bf970"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact_group_members",
        "type",
        existing_type=sa.Enum("EMAIL", "IRC"),
        type_=mysql.ENUM("EMAIL", "IRC", "PHAB"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact_group_members",
        "type",
        existing_type=sa.Enum("EMAIL", "IRC", "PHAB"),
        type_=mysql.ENUM("EMAIL", "IRC"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
