'''add global alert rules table

Revision ID: 1a404a44c724
Revises: 0ea6b0444581
Create Date: 2021-08-03 10:37:34.452952

'''
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a404a44c724'
down_revision = '0ea6b0444581'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'global_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('query', sa.String(length=2048), nullable=True),
        sa.Column('duration', sa.String(length=32), server_default='1m', nullable=False),
        sa.Column('severity', sa.String(length=32), server_default='warn', nullable=False),
        sa.Column('annotations', sa.JSON(), nullable=False),
        sa.Column(
            'mode',
            sa.Enum('PER_PROJECT', 'GLOBAL'),
            server_default='PER_PROJECT',
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='u_name'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_alerts')
    # ### end Alembic commands ###
