"""expr is not nullable

Revision ID: 85f1d58f533d
Revises: ea4c92eef10c
Create Date: 2021-08-03 10:55:38.991648

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "85f1d58f533d"
down_revision = "ea4c92eef10c"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alerts", "expr", existing_type=mysql.VARCHAR(length=2048), nullable=False
    )
    op.alter_column(
        "global_alerts",
        "expr",
        existing_type=mysql.VARCHAR(length=2048),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "global_alerts", "expr", existing_type=mysql.VARCHAR(length=2048), nullable=True
    )
    op.alter_column(
        "alerts", "expr", existing_type=mysql.VARCHAR(length=2048), nullable=True
    )
    # ### end Alembic commands ###
