"""blackbox dns support

Revision ID: a4ae1f9b9703
Revises: d11beaad341c
Create Date: 2023-09-25 13:04:26.008154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4ae1f9b9703"
down_revision = "d11beaad341c"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrape_blackbox_dns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scrape_id", sa.Integer(), nullable=True),
        sa.Column("query_name", sa.String(length=255), nullable=False),
        sa.Column("query_type", sa.String(length=255), nullable=False),
        sa.Column("require_answer_match", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["scrape_id"], ["scrapes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scrape_id"),
    )

    op.alter_column(
        "scrapes",
        "scheme",
        type_=sa.Enum("tcp", "udp", "http", "https"),
        server_default="http",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scrape_blackbox_dns")
    op.alter_column(
        "scrapes",
        "scheme",
        type_=sa.Enum("http", "https"),
        server_default="http",
        nullable=False,
    )
    # ### end Alembic commands ###
