"""create openstack_supported_images table

Revision ID: b69fcb1d4f08
Revises: 7d6e58ad6d25
Create Date: 2023-06-30 22:36:11.550168

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b69fcb1d4f08"
down_revision = "7d6e58ad6d25"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openstack_supported_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openstack_id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("openstack_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("openstack_supported_images")
    # ### end Alembic commands ###
