'''add scrape scheme

Revision ID: c3147c5d7f41
Revises: 8d332a4bfe2f
Create Date: 2021-10-23 17:00:36.590949

'''
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c3147c5d7f41'
down_revision = '8d332a4bfe2f'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scrapes',
        sa.Column('scheme', sa.Enum('http', 'https'), server_default='http', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrapes', 'scheme')
    # ### end Alembic commands ###
