"""add host to blackbox http

Revision ID: d11beaad341c
Revises: 2b4baa8d146a
Create Date: 2023-09-09 19:23:36.337424

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d11beaad341c"
down_revision = "2b4baa8d146a"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrape_blackbox_http", sa.Column("host", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrape_blackbox_http", "host")
    # ### end Alembic commands ###
