"""add contact group members table

Revision ID: e5712abd9572
Revises: 14fe695ed85b
Create Date: 2021-08-05 15:02:51.494883

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5712abd9572"
down_revision = "14fe695ed85b"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_group_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_group_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("EMAIL", "IRC"), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_group_id"], ["contact_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_group_members")
    # ### end Alembic commands ###
