#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2021-2024 Taavi Väänänen <hi@taavi.wtf>
# SPDX-License-Identifier: AGPL-3.0-only
"""
Open an interactive shell with app context ready.
"""
import code

from prometheus_manager.app import create_app

app = create_app("ADMIN")

with app.app_context():
    code.interact(
        banner="--- prometheus-manager interactive shell ---", local={"app": app}
    )
