#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2021-2024 Taavi Väänänen <hi@taavi.wtf>
# SPDX-License-Identifier: AGPL-3.0-only
"""
Perform database migrations.
"""
from prometheus_manager.app import create_app

app = create_app("ADMIN")

with app.app_context():
    from prometheus_manager.database import alembic

    alembic.upgrade()
